import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"


export const metadata = {
  title: "Patrick's Resturant App",
  description: "Generated by GPN",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased text-lg bg-gray-100 min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
