import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"
import Provider from "../provider/ReactQueryProvider";
import { UserProvider } from "../context/UserContext"; // ✅ import UserProvider

export const metadata = {
  title: "Ceccy Ann Resturant App",
  description: "Generated by GPN",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased text-lg bg-gray-100 min-h-screen flex flex-col">
        <UserProvider>  {/* ✅ Wrap the app in UserProvider */}
          <Provider>
            <Navbar />
            <main className="flex-1">{children}</main>
            <Footer />
          </Provider>
        </UserProvider>
      </body>
    </html>
  );
}
